name: Terraform Plan (OIDC)

on:
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  plan:
    runs-on: ubuntu-latest
    environment: prod

    env:
      TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD }}
      TF_VAR_certificate_arn: ${{ secrets.TF_VAR_CERTIFICATE_ARN }}

    defaults:
      run:
        shell: bash
        working-directory: environments/dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::396081123408:role/GitHubActionsTerraformRole
          aws-region: us-east-1
          role-session-name: GitHubActions-Terraform-Plan

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform fmt (check)
        run: terraform fmt -check -recursive

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -input=false -no-color
